### PR TITLE
#301 Remove Venmo Billing Option

### PR DESCRIPTION
**Pull request by brittanygay**
Connected to #301 

- Hid the Venmo Billing Option on the Billing page from Accounts > Billing

Assigning to @daybreaker since this is just a js update

screen shot 2018-11-29 at 2 51 13 pm

### CODE REVIEW

**Comment by daybreaker** [comment]
I think we should just hide the billing page all together right now? With the Stripe Web View, it's not storing payment methods, so we cant list anything for the time being.

**Comment by brittanygay** [comment]
Ah that's a good call. Pulling in @Mcscott142 to see what he thinks/if we should update the AC and hide the entire billing page

**Comment by Mcscott142** [comment]
Got it, didn't realize that. Yeah just hide the Billing info link altogether on the account. Not much happening on this page for initial go round. @brittanygay

**Comment by brittanygay** [comment]
I just updated to hide the Billing page altogether.

**Pull request merged**
