### PR TITLE
Change ticket price to "SOLD OUT" when ticket is sold out

### PR DESCRIPTION
**Pull request by bryanjos**
connects to #677 

Simulator Screen Shot - iPhone XR - 2019-03-28 at 12 54 52

### CODE REVIEW

**Comment by zmelamed** [comment]
This wasn't written correctly. The ticket price should change to sold out not ticket name

**Comment by zmelamed** [comment]
Will need to reduce the font size down when it's marked sold out. Can make the font size match the ticket name font size for sold out tix until we can throw a designer on it

**Comment by bryanjos** [comment]
Updated

**Comment by bryanjos** [comment]
I'm tackling now. Please do not merge yet

**Comment by bryanjos** [comment]
Updated:

Simulator Screen Shot - iPhone XR - 2019-03-28 at 12 54 52

**Pull request merged**
