### PR TITLE
transfer tix

### PR DESCRIPTION
**Pull request by jwietelmann**
connect #420

### CODE REVIEW

**Comment by Mcscott142** [comment]
The web has issues with the Transfer process right now and we'd like to get @daybreaker's eyes on the PR when he's back. Holding tight on getting this merged.

**Comment by Mcscott142** [comment]
Commented on https://github.com/revelrylabs/bn-mobile-react/issues/421 with the issue blocking us from merging.

**Comment by Krakaw** [comment]
https://github.com/big-neon/bn-api/issues/847#issuecomment-452620606

**Comment by Mcscott142** [comment]
This one is good for review now. Ticket transfer problems have been handled on Web side. cc @jwietelmann @daybreaker

**Comment by Mcscott142** [comment]
but conflicts

**Comment by jwietelmann** [comment]
Not quite. This has to be deployed first: https://github.com/big-neon/bn-api/pull/861

**Comment by jwietelmann** [comment]
(And after that gets merged, we need to make some additional changes so that transferred tickets show up in the right place.)

**Comment by Mcscott142** [comment]
Is this one ready for review/merge (after conflicts fixed) or do we need more direction on ticket transfers @jwietelmann?

**Comment by jwietelmann** [comment]
It's gonna be ready today

**Pull request merged**
