### PR TITLE
When a promo code is entered, the button text changes to...

### PR DESCRIPTION
**Pull request by bryanjos**
"Remove Promo Code".

connects to #524

Still have to add check image. Probably needed a designer's help

simulator screen shot - iphone xr - 2019-02-26 at 14 44 54

simulator screen shot - iphone xr - 2019-02-26 at 14 44 58

### CODE REVIEW

**Comment by brittanygay** [comment]
@bryanjos I just pushed up edits for the design pass for the check icon.

I added a stubbed out section in `tickets.js` (lines 95-102) because right now the "applied" code just sits in the input, which shouldn't be the case when it's applied. It's using a placeholder code right now, too, but you'll need to set this up to show only when it should and add the functionality for the code to work in my stubbed out section.

Let me know if you'd like to pair! I might take one more look once you have everything set up because I want to clean up the alignment once the code is in the right place.

Assigning to @CheetoMao for a quick design review of my updates.

screen shot 2019-02-27 at 12 58 38 pm

**Comment by bryanjos** [comment]
@brittanygay thank you! I have hooked everything up and this should be good to go

**Comment by CheetoMao** [comment]
@brittanygay so this looks good and matches the suggested mocks. But it totally looks like I should click on the 'review promo code' button moreso than anything else on this screen. I might be out of touch with this project, but just looking at the screenshot, Im not sure what a user *should* do once they've added a successful promo code. (Click the back button? Click on the ticket row? Close the app?)

**Comment by bryanjos** [comment]
@CheetoMao I honestly had the same confusion when I first started working on this. I think it's something worth a discussion. 

It's not related directly to the changes here though

**Comment by brittanygay** [comment]
@CheetoMao I also totally agree with this!

For Big Neon, they have their own design team who does the design work and then they pass over the mocks. I'm working on the implementation side only, _but_ they are always open to suggestions, so this is something worth bringing up!

**Comment by zmelamed** [comment]
This is really great feedback and I appreciate you all bringing it forward. @CheetoMao @brittanygay any suggestions on how to make the ticket types a bit more clickable would be much appreciated

**Comment by brittanygay** [comment]
@zmelamed @CheetoMao I'm going to break out a new ticket where we can further discuss some UX updates to this userflow

**Pull request merged**
